# Generated by Django 6.0.6 on 2026-09-02 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='signup_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='times_visited',
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(default='JSA Clubroom / University Centre', max_length=255)),
                ('times_visited', models.PositiveIntegerField(default=0)),
                ('signup_link', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_occurrences', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='main.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
