# Generated by Django 6.0 on 2026-07-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_event_date_remove_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
