# Generated by Django 6.0.6 on 2026-09-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_time_event_start_time_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='STEM 404', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='location',
            field=models.CharField(default='STEM 404', max_length=50),
        ),
    ]
