# Generated by Django 6.0.6 on 2026-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_location_alter_eventsession_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='name',
            field=models.CharField(default='Session', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='times_visited',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
