# Generated by Django 6.0 on 2026-07-08 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='header_image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
