# Generated by Django 6.0.6 on 2026-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eventsession_name_alter_eventsession_times_visited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsession',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='eventsession',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this box to highlight this event on the home page or in the calendar banner.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CULTURE', 'Culture'), ('LANGUAGE', 'Language'), ('COMMUNITY', 'Community'), ('FESTIVAL', 'Festival')], default='CULTURE', max_length=20),
        ),
    ]
