# Generated by Django 6.0.6 on 2026-09-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_eventsession_options_eventsession_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.CharField(default='See you there!', help_text="'Note' field in event main page.", max_length=40),
        ),
    ]
