# Generated by Django 6.0.6 on 2026-09-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering')], default='calendar', help_text='Select an icon to display on event cards and banners.', max_length=20)),
                ('header', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='main.event')),
            ],
        ),
    ]
