# Generated by Django 6.0.6 on 2026-09-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave blank if the exact time is TBD.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave blank if the exact time is TBD.', null=True),
        ),
    ]
