# Generated by Django 6.0.6 on 2026-09-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_component_text_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.TextField(default='default banner text'),
            preserve_default=False,
        ),
    ]
