# Generated by Django 6.0.6 on 2026-09-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
