# Generated by Django 6.0.6 on 2026-09-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='icon',
            field=models.CharField(choices=[('question', 'Question Mark'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering')], default='calendar', help_text='Select an icon to display on event cards and banners.', max_length=20),
        ),
    ]
