# Generated by Django 6.0.6 on 2026-09-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_component_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('question', 'Question Mark'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display on the card.', max_length=20)),
                ('header', models.CharField()),
                ('text', models.TextField()),
                ('event_session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.eventsession')),
            ],
        ),
    ]
