# Generated by Django 6.0.6 on 2026-09-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.component'),
        ),
        migrations.AlterField(
            model_name='card',
            name='event_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.eventsession'),
        ),
        migrations.AlterField(
            model_name='component',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='main.event'),
        ),
    ]
