# Generated by Django 6.0.6 on 2026-09-08 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_card_component_alter_card_event_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='component',
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('question', 'Question Mark'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display on event cards and banners.', max_length=20)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='main.event')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.container'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
