# Generated by Django 6.0.6 on 2026-09-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_card_component_container_card_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='event_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.eventsession'),
        ),
        migrations.AlterField(
            model_name='card',
            name='header',
            field=models.CharField(default='Header Text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display to the left of the text.', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default='Loren Ipsum'),
        ),
        migrations.AlterField(
            model_name='container',
            name='icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display on event cards and banners.', max_length=20),
        ),
    ]
