# Generated by Django 6.0.6 on 2026-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_eventsession_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsession',
            name='times_visited',
        ),
        migrations.AddField(
            model_name='eventsession',
            name='description',
            field=models.TextField(default='sample', help_text="Optional. If empty, will default to parent event's description."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsession',
            name='room',
            field=models.CharField(default='STEM 404', help_text='Optional. (e.g., STEM 404)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='capacity',
            field=models.PositiveIntegerField(default=30, help_text='Leave as 0 for sessions  with no capacity restriction.'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Leave as 0.00 to label as Free.', max_digits=2),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this box to highlight this session on the home page or in the calendar banner.'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='location',
            field=models.CharField(help_text='Building / Park. (e.g., STEM Complex)', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text="Event page register button marked as  'Not Available Yet' after deadline.", null=True),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='signup_link',
            field=models.URLField(blank=True, help_text='Optional. Link to registration form.', max_length=500, null=True),
        ),
    ]
