# Generated by Django 6.0.6 on 2026-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_eventsession_times_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='description',
            field=models.TextField(blank=True, help_text="Optional. If empty, will default to parent event's description."),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='room',
            field=models.CharField(blank=True, help_text='Optional. (e.g., STEM 404)', max_length=50),
        ),
    ]
