# Generated by Django 6.0.6 on 2026-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_eventsession_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsession',
            name='description',
        ),
        migrations.AddField(
            model_name='eventsession',
            name='banner',
            field=models.TextField(blank=True, help_text='Optional. If empty, will default to parent event banner.'),
        ),
    ]
