# Generated by Django 6.0.6 on 2026-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_eventsession_description_eventsession_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='signup_link',
            field=models.URLField(blank=True, help_text='Optional. Leave empty for Drop-in / Walk-in events.', max_length=500, null=True),
        ),
    ]
