# Generated by Django 6.0.6 on 2026-09-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_eventsession_signup_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('location', 'Map / Location'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display to the left of the text.', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('location', 'Map / Location'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='calendar', help_text='Select an icon to display on event cards and banners.', max_length=20),
        ),
    ]
