# Generated by Django 6.0.6 on 2026-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_card_icon_alter_container_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(blank=True, default='STEM 404', help_text='Optional. Leave blank if room is TBD.', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='STEM Complex', help_text='Optional. Leave blank if the exact location is TBD.', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text="Event register button marked as  'Not Available Yet' after deadline. Leave empty for Drop-in / Walk-in events.", null=True),
        ),
    ]
