# Generated by Django 6.0.6 on 2026-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_event_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Every Week'), (2, 'Every Other Week'), (3, 'Monthly'), (4, 'Every Semester'), (5, 'Yearly'), (6, 'One-off')], help_text='Optional. Fall back if day of the week TDB.', null=True),
        ),
    ]
