# Generated by Django 6.0.6 on 2026-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_event_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Every Week'), (2, 'Every Other Week'), (3, 'Monthly'), (4, 'Every Semester'), (5, 'Yearly'), (6, 'One-off')], default=2, help_text='Determines formatting in event page right-side detail card.'),
            preserve_default=False,
        ),
    ]
