# Generated by Django 6.0.6 on 2026-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_event_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Every Week'), (2, 'Every Other Week'), (3, 'Every Month'), (4, 'Every Semester'), (5, 'Every Fall Semester'), (6, 'Every Winter Semester'), (7, 'Every Summer Semester'), (8, 'Every Year'), (9, 'One-off')], default=1, help_text='Determines formatting in event page right-side detail card.'),
        ),
    ]
