# Generated by Django 6.0.6 on 2026-09-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Optional. Additional information text under album', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='additional_info_icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('location', 'Map / Location'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='location', help_text='Select an icon to display on event cards and banners.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.TextField(help_text='Event description that will appear in banner.'),
        ),
    ]
