# Generated by Django 6.0.6 on 2026-09-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_album_additional_info_album_additional_info_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Optional. Additional information text under album', max_length=50),
        ),
    ]
