# Generated by Django 6.0.6 on 2026-09-16 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_album_additional_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='updated_at',
            new_name='last_edited_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='last_edited_at',
        ),
        migrations.RenameField(
            model_name='eventsession',
            old_name='updated_at',
            new_name='last_edited_at',
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='eventsession',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Optional. Leave blank to default to Location.', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='additional_info_icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('location', 'Map / Location'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='location', help_text='Select an icon to display next to the additional info.', max_length=20),
        ),
    ]
