# Generated by Django 6.0.6 on 2026-09-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_updated_at_album_last_edited_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
    ]
