# Generated by Django 6.0.6 on 2026-09-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_image_photo_photo_remove_photo_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='file',
        ),
    ]
