# Generated by Django 6.0.6 on 2026-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_photo_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='semester_slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
