# Generated by Django 6.0.6 on 2026-10-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_album_event_slug_album_semester_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Custom label next to icon. Leave blank to use Location.', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='additional_info_icon',
            field=models.CharField(choices=[('info', 'Info / Note'), ('question', 'Question / What is?'), ('clock', 'Clock / Time'), ('location', 'Map / Location'), ('bell', 'Bell / Notification'), ('calendar', 'Calendar'), ('star', 'Star / Featured'), ('users', 'People / Gathering'), ('none', 'None')], default='location', help_text='Custom icon for additional info.', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(editable=False, help_text='Auto-generated. Derived from session date.'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tag_name',
            field=models.CharField(help_text='Custom text label that goes above album card.', max_length=50),
        ),
    ]
