# Generated by Django 6.0.6 on 2026-10-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_album_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
    ]
